global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "reclaim-server"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["https://reclaim-backend-q8iq.onrender.com"]